### ISSUE TITLE
tufte + knitr/rmarkdown + servr + jekyll

### ISSUE THREAD

**Issue by dfeng** [rstudio/tufte#11]
I am currently running a mashup of jekyll/rmarkdown/tufte/servr to render my research blog, and it employs several workarounds. I'm hoping that by outlining such workarounds, it'll start a dialogue on how best to support such a system. And perhaps people who are trying something similar will find this useful.

Based on your [build.R](https://github.com/yihui/knitr-jekyll/blob/gh-pages/build.R) from knitr-jekyll, I have a similar [version](https://gist.github.com/dfeng/fbd262b663b3999f109d), the biggest difference being that instead of running `knitr::knit`, I run `rmarkdown::render`, so that I can take advantage of the `tufte` html styles.

This then introduces a host of problems:
- There is no option right now to leave the frontmatter intact, which is very important for jekyll, naturally. My first hack is to change `tufte/R/html.R` in the `tufte` package to manually reinstate the frontmatter. Originally, I thought I could just pass a post_processor to do that work, but it turns out that html_documents already have a post_processor, and since there's no chaining, the post-processor I pass in will just be replaced.
- The location of figures gets overrun, L265 of [render.R](https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L265) in rmarkdown, and since I want to specify the location of my figures depending on the post I'm rendering, I've simply commented out those 4 lines, and set them up in my `build.R` file.
- There is some filename wizardry being done by `servr::jekyll` – _source to _post for instance – that calls for some manual renaming when combined with `rmarkdown`. Also `tufte_html` outputs a html file, which we then need to rename into `.md` (my custom `template.html` is basically `$body$`). All this can be found in my `build.R`. One solution here would be to have something like a `tufte_md` class perhaps?

Right now, this setup works for me, but it's obviously a series of temporary hacks that will one day fail.

**Comment by yihui** [comment]
Two things:

1. I have been hoping to rewrite Jekyll with R and R Markdown, but I have not really thought carefully about it. Jekyll is slow and boring to me, and I believe we can do a much much better job with R Markdown. The slight downside is what you will push to Github pages are HTML pages instead of Markdown, but I don't think that is big deal. Since you have dug so deep into rmarkdown, I guess you may think more about it. If you are still a student, we can do a GSOC project this in a couple of months: https://github.com/rstats-gsoc/gsoc2016/wiki/table-of-proposed-coding-projects I'm talking about this to you because I found your website http://dfeng.github.io looked beautiful, so presumably you must have got the skills needed for the GSOC project.
2. Talking about a research blog, I guess this package may be more helpful to you: https://github.com/rstudio/bookdown It is mostly done now, and I just need one more week to document the work.

**Comment by mwilliams2921** [comment]
I'm not a student (and I doubt I have the skills needed for GSOC anyway) but I'd like to second this request. My ideal would be something like what the OP described. I currently use rstudio/knitr, jekyll, and gitlab to host a research blog. It largely works but I've had to hack my way to including htmlwidgets and feel that it isn't worth pursuing a tufte style as it's likely to be difficult to maintain w/ dependency updates. If you haven't seen it [Airbnb describes something similar on Medium](https://medium.com/airbnb-engineering/scaling-knowledge-at-airbnb-875d73eff091#.i5qat46hr). The use of pull requests for research quality control never even occurred to me (I don't work with a team of R users) but they're basically describing jekyll/knitr/github pages. Everyone has their own preferences but I think getting all this from simply pushing to a repo is very very appealing. 

To be clear I'm not advocating for ultimately using jekyll. But I would say that a static site generator from rstudio with support for all your new rmarkdown formatting, themes, htmlwidgets, etc might be worth prioritizing. I think this knowledge repository idea has legs.

**Comment by yihui** [comment]
- blogdown has been born: https://github.com/rstudio/blogdown
- and there is a tufte theme (not based on this tufte package): https://github.com/nstrayer/tuftesque
