### ISSUE TITLE
Print on paper, control page size and pagebreaks

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/tufte#14]
Since tufte html already looks very nice, in many cases it can immediately be used to created printed document. It would be handy if for these purposes there was a mechanism to set page size of the paper and also force manual page breaks in the document. Is there a way to do this?
If not, could such a mechanism be added?

**Comment by yihui** [comment]
I'd just use `tufte::tufte_handout` instead.

**Comment by 1beb** [comment]
@neuwirthe I use the page model for css combined with [weasyprint](http://weasyprint.org) on the html version. Here's some example css, that you would include in your yaml header: 

```
output:
  tufte::tufte_html:
    css: your_file.css
```

It does the following: 

* prints in landscape
* forced page break on h1, h2 (in markdown that's headings at `#` and `##` levels)
* adjusts the page sideways a little so that margin figures are displayed
* adds a copyright notice and page numbering to every page, other than the first.

```
@media print {
  body {
    background-image: none;
    padding-left:0.75cm;
    width: 100%;
  }

  table {
    margin-top: 15px;
    width: auto;
    max-width: 100%;
  }
  
  td {
    padding:0 3px;
  }

  h1, h2 {
    margin:0 0 0.25cm 0;
    page-break-before: always;
  }

  .figure {
    page-break-inside: avoid;
  }

  @page {
    margin: 1cm 0.75cm 1cm 0.75cm;
  }

  @page :first{
    margin:0;
    @bottom-left {content: "";}
    @bottom-right {content: "";}
  }
  
  @page {
    size: landscape; 
    @bottom-left {
      content: "© My Special Company";
    }
    @bottom-right {
      content: counter(page);
    }
  }  
}
```

Step 1. Knit
Step 2. Review html
Step 3. `python -m weasyprint your_file.html ~/path/to/pdf.pdf`
