### ISSUE TITLE
fonts in inst/rmarkdown/templates/tufte_html/resources/et-book are marked executable

### ISSUE THREAD

**Issue by josch** [rstudio/tufte#69]
The fonts in `inst/rmarkdown/templates/tufte_html/resources/et-book` are all marked as executable. But they are fonts. They should not be marked as executable.

**Comment by yihui** [comment]
Would you `chmod -x *.ttf` and submit a pull request? Thanks!

**Comment by josch** [comment]
Really? Writing this message took you probably a similar amount of keystrokes that it would've taken to run `chmod` and `git add` and `git commit` yourself... :/

**Comment by josch** [comment]
And there it is.

**Comment by mschilli87** [comment]
@josch:
> Writing this message took you probably a similar amount of keystrokes that it would've taken to run `chmod` and `git add` and `git commit` yourself... :/

Given that your initial issue text was even longer, why didn't you send a PR right away?
I'm sure @yihui did not ask you to do a PR because he is lazy but because he has many projects to maintain and would have much more time for important things if trivial improvements like this would come with a solution instead of just pointing out the problem. :wink:

But please don't get me wrong: Thx for you contribution and thx for opening the PR regardless of your opinon. :handshake:
